export const ADD_MOBILE = 'ADD_MOBILE'
export const ADD_PRODUCTS = 'ADD_MOBILES'

export const ADD_LAPTOP = 'ADD_LAPTOP'
export const ADD_CODE_ORDER = 'ADD_CODE_ORDER'

export const COUNT_PRODUCT = 'COUNT_PRODUCT'
export const UP_COUNT_PRODUCT = 'UP_COUNT_PRODUCT'
export const DOWN_COUNT_PRODUCT = 'DOWN_COUNT_PRODUCT'

export const ADD_TO_CART = 'ADD_TO_CART'
export const UPDATE_TO_CART = 'UPDATE_TO_CART'
export const DELETE_ITEM_CART = 'DELETE_ITEM_CART'