export const FETCH_CHAT = 'FETCH_TASK';

export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS';
export const FETCH_CHAT_FAILED = 'FETCH_CHAT_FAILED';

export const FILTER_CHAT = 'FILTER_CHAT';
export const FILTER_CHAT_SUCCESS = 'FILTER_CHAT_SUCCESS';

export const ADD_CHAT = 'ADD_CHAT';
export const ADD_CHAT_SUCCESS = 'ADD_CHAT_SUCCESS';
export const ADD_CHAT_FAILED = 'ADD_CHAT_FAILED';

export const SET_CHAT_EDITTING = 'SET_CHAT_EDITTING';

export const UPDATE_CHAT = 'UPDATE_CHAT';
export const UPDATE_CHAT_SUCCESS = 'UPDATE_CHAT_SUCCESS';
export const UPDATE_CHAT_FAILED = 'UPDATE_CHAT_FAILED';

export const DELETE_CHAT = 'DELETE_CHAT';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FAILED = 'DELETE_CHAT_FAILED';