export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const CHANGE_BG_CREATE = 'CHANGE_BG_CREATE';
export const CHANGE_BG_EDIT = 'CHANGE_BG_EDIT';
export const CHANGE_BG_DELETE = 'CHANGE_BG_DELETE';

export const CHANGE_MODAL_TITLE = 'CHANGE_MODAL_TITLE';
export const CHANGE_MODAL_CONTENT = 'CHANGE_MODAL_CONTENT';